version: '3.4'

services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - website
    restart: always

networks:
  network:
    driver: bridge
